name: Checking workflows

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: 'none'
      environment:
        type: string
        required: true
        default: 'none'
      cluster_name:
        type: string
        required: true
        default: 'none'
      user_name:
        type: string
        required: false
        default: 'none'
      password:
        type: string
        required: false
        default: 'none'

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: check parametros de entrada
        run: |
         if [[ '${{ github.event.inputs.version }}' == 'none' ]]; then
          echo "Version no valida"
          exit 1
         fi
          echo "version valida"

  check_environment:
    runs-on: ubuntu-latest
    steps:
      - name: check parametros de entrada
        run: |
          if [[ '${{ github.event.inputs.environment }}' == 'none' ]]; then
          echo "environment no valida"
          exit 1
          fi
          echo "environment valida"

  check_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: check parametros de entrada
        run: |
          if [[ '${{ github.event.inputs.cluster_name }}' == 'none' ]]; then
          echo "cluster_name no valida dsda"
          exit 1
          fi
          echo "cluster_name valida"

  call_workflow_check:
    uses: ./.github/workflows/workflow_called.yml
    with:
      user_name: ${{github.event.inputs.user}}
      password: ${{github.event.inputs.password}}